# This policy will always approve every PR.

policy:
  approval:
  - no approval necessary
  - or:
    - foo owner approves
    - backup foo owner approves
    - other engineers override foo approval
  - bar

approval_rules:
- name: no approval necessary
- name: foo owner approves
  description: "See go/policy/foo"
  if:
    changed_files:
      paths:
        - "^foo*"
  options:
    allow_author: true
    allow_contributor: true
    invalidate_on_push: true
    methods:
      comment_patterns:
        - "(?m)^approve for foo\\b"
      github_review: true
  requires:
    count: 1
    permissions: ["write"]
- name: backup foo owner approves
  description: "See go/policy/foo"
  if:
    changed_files:
      paths:
        - "^foo*"
  options:
    allow_author: true
    allow_contributor: true
    invalidate_on_push: true
    methods:
      comment_patterns:
        - "(?m)^approve for foo-backup\\b"
      github_review: false
  requires:
    count: 1
    permissions: ["write"]
- name: other engineers override foo approval
  description: "See go/policy/foo"
  if:
    changed_files:
      paths:
        - "^foo*"
  options:
    allow_author: true
    allow_contributor: true
    invalidate_on_push: true
    methods:
      comment_patterns:
        - "(?m)^approve for foo-override\\b"
      github_review: false
  requires:
    count: 2
    permissions: ["write"]

- name: bar
