name: 'Brad Bot'
description: 'enforce things'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  GITHUB_TOKEN:
    description: 'Authorization Token for accessing GitHub'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: composite
  steps:
  - uses: actions/setup-go@v2
    with:
      go-version: '1.20.x'
  - run: echo Hello ${{ inputs.who-to-greet }}.
    shell: bash
  - run: go run ./hi.go -- ${{ inputs.GITHUB_TOKEN }}
    shell: bash
  - id: random-number-generator
    run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
    shell: bash
  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - run: goodbye.sh
    shell: bash
